apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: '#(deploy-name)#'
    group: fuse7-java-openshift
    version: '#(version.service)#'
  name: #(deploy-name)#-properties
data:
  #(deploy-name)#.properties: >-
  
    ### Variables globales de log y camel ###
    
    ### Variables para base de datos replica ###

    database.bscs.url=#(prop.database.bscs.url)#

    database.bscs.port=#(prop.database.bscs.port)#

    database.bscs.host=#(prop.database.replica.host)#
    
    database.bscs.databasename=#(prop.database.bscs.databasename)#

    database.bscs.username=#(prop.database.replica.username)#

    database.bscs.password=#(prop.database.replica.password)#

    ### Variables para servicio REST ###

    service.rest.host=#(prop.service.rest.host)#

    service.rest.port=#(prop.service.rest.port)#

    service.rest.resource=#(prop.service.rest.resource)#
