apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: fuse7-java-openshift-wom-rest-appdynamics
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        component: '${APP_NAME}'
        group: fuse7-java-openshift
        version: '${APP_VERSION}'
      name: '${APP_NAME}'
    spec:
      clusterIP: None
      deprecatedPublicIPs: []
      ports:
        - name: service-soap
          port: 8888
          protocol: TCP
          targetPort: 8888
        - name: service-rest
          port: 8889
          protocol: TCP
          targetPort: 8889
      selector:
        component: '${APP_NAME}'
        group: fuse7-java-openshift
        version: '${APP_VERSION}'
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      labels:
        component: '${APP_NAME}'
        group: fuse7-java-openshift
        version: '${APP_VERSION}'
      name: '${APP_NAME}'
    spec:
      replicas: 1
      selector:
        component: '${APP_NAME}'
        group: fuse7-java-openshift
        version: '${APP_VERSION}'
      strategy:
        resources: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            component: '${APP_NAME}'
            group: fuse7-java-openshift
            version: '${APP_VERSION}'
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: JAVA_OPTIONS
                  value: >-
                    ${JAVA_OPTIONS}
                - name: APP_ENV
                  value: '${APP_ENV}'
                - name: APPDYNAMICS_CONTROLLER_HOST_NAME
                  value: '${APPDYNAMICS_CONTROLLER_HOST_NAME}'
                - name: APPDYNAMICS_CONTROLLER_PORT
                  value: '${APPDYNAMICS_CONTROLLER_PORT}'
                - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
                  value: '${APPDYNAMICS_CONTROLLER_SSL_ENABLED}'
                - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
                  value: '${APPDYNAMICS_AGENT_ACCOUNT_NAME}'
                - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
                  value: '${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}'
                - name: APPDYNAMICS_AGENT_APPLICATION_NAME
                  value: '${APP_NAME}'
                - name: TZ
                  value: '${TZ}'
                - name: APPDYNAMICS_AGENT_TIER_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: APPDYNAMICS_AGENT_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              image: 'library/${APP_NAME}:${IMAGE_TAG}'
              livenessProbe:
                initialDelaySeconds: 180
                tcpSocket:
                  port: 8888
              name: '${APP_NAME}'
              ports:
                - containerPort: 8888
                  name: service-soap
                - containerPort: 8889
                  name: service-rest
                - containerPort: 8778
                  name: jolokia
              readinessProbe:
                initialDelaySeconds: 20
                tcpSocket:
                  port: 8889
              volumeMounts:
              - mountPath: /etc/config
                name: volume-properties-file
          volumes:
          - configMap:
              defaultMode: 420
              name: ${APP_NAME}-properties
            name: volume-properties-file
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - '${APP_NAME}'
            from:
              kind: ImageStreamTag
              name: '${APP_NAME}:${IMAGE_TAG}'
          type: ImageChange
    status: {}
parameters:
  - description: The name assigned to the application.
    displayName: Application Name
    name: APP_NAME
    required: true
  - description: The application version.
    displayName: Application Version
    name: APP_VERSION
    required: true
  - description: Properties file path.
    displayName: Properties file
    name: APP_ENV
    required: true
  - description: Image tag that will be used.
    displayName: Image Stream tag
    name: IMAGE_TAG
    required: true
  - description: Limits for use to the JVM.
    displayName: JVM Memory configuration
    name: JAVA_OPTIONS
    required: true
    value: >-
      -Xmx100m -Xss256k -XX:MetaspaceSize=16m -XX:MaxMetaspaceSize=64m
      -XX:CompressedClassSpaceSize=32M -XX:ReservedCodeCacheSize=16M
      -XX:NativeMemoryTracking=summary -XX:MaxHeapFreeRatio=70
  - description: AppDynamics Controller Host
    displayName: AppDynamics Controller Host
    name: APPDYNAMICS_CONTROLLER_HOST_NAME
  - description: AppDynamics Controller Port
    displayName: AppDynamics Controller Port
    name: APPDYNAMICS_CONTROLLER_PORT
  - description: AppDyanamics SSL Enabled
    displayName: AppDyanamics SSL Enabled
    name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
  - description: AppDynamics Agent Account Name
    displayName: AppDynamics Agent Account Name
    name: APPDYNAMICS_AGENT_ACCOUNT_NAME
  - description: AppDynamics Agent Acount Key
    displayName: AppDynamics Agent Acount Key
    name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
  - description: Time Zone
    displayName: Time Zone
    name: TZ
    required: true
    value: America/Santiago
  - description: Logs Level
    displayName: Logs Level
    name: LOGLEVEL
    required: true
    value: INFO
